import uuid
from datetime import datetime

from sqlalchemy import ForeignKey, func
from sqlalchemy.orm import Mapped, declared_attr, mapped_column


class UUIDPrimaryKeyMixin:
    """UUID primary key, generated by Postgres (`pgcrypto`) so it exists
    even for rows inserted outside the ORM. See docs/DATABASE.md §2.
    """

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, server_default=func.gen_random_uuid())


class TimestampMixin:
    """Standard audit timestamps applied to every table (docs/DATABASE.md §2)."""

    created_at: Mapped[datetime] = mapped_column(server_default=func.now())
    updated_at: Mapped[datetime | None] = mapped_column(onupdate=func.now())


class AuditUserMixin:
    """Standard created_by/updated_by applied to every table (docs/DATABASE.md §2).

    Nullable because system/scheduler-originated rows have no acting user.
    """

    @declared_attr
    def created_by(cls) -> Mapped[uuid.UUID | None]:
        return mapped_column(ForeignKey("users.id"), nullable=True)

    @declared_attr
    def updated_by(cls) -> Mapped[uuid.UUID | None]:
        return mapped_column(ForeignKey("users.id"), nullable=True)


class SoftDeleteMixin:
    """Applied only to master/reference-data tables — see the per-entity
    "soft-delete: yes/no" note in docs/DATABASE.md §4.
    """

    is_deleted: Mapped[bool] = mapped_column(default=False, server_default="false")
    deleted_at: Mapped[datetime | None] = mapped_column(nullable=True)
