"""add rag_document_chunks with pgvector

Revision ID: 544a1f8f92c8
Revises: fbce44b1d9f5
Create Date: 2026-08-03 00:54:34.507219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '544a1f8f92c8'
down_revision: Union[str, Sequence[str], None] = 'fbce44b1d9f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Not auto-generated: pgvector's Postgres extension itself. Idempotent,
    # so this is also how a fresh checkout gets it via `alembic upgrade
    # head` alone — no separate manual `CREATE EXTENSION` step required.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rag_document_chunks',
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=768), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # No ivfflat/hnsw index: at this knowledge base's current size (a
    # handful of files, dozens of chunks), a plain sequential scan over the
    # cosine-distance operator is both correct and fast — an approximate-
    # nearest-neighbor index adds complexity (and, on this little data,
    # genuinely worse recall) for no real benefit yet. Add one if the
    # knowledge base grows substantially.
    op.create_index('ix_rag_document_chunks_source', 'rag_document_chunks', ['source'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rag_document_chunks_source', table_name='rag_document_chunks')
    op.drop_table('rag_document_chunks')
    # ### end Alembic commands ###

    # Deliberately NOT dropping the vector extension here — see
    # docs/DATABASE.md §8's Phase 6 note. The app's own migration role
    # can create it (CREATE EXTENSION IF NOT EXISTS succeeds even for a
    # non-superuser when it already exists) but cannot drop it (DROP
    # EXTENSION requires ownership), confirmed by actually running this
    # downgrade against Postgres 16. A shared, cluster-level extension
    # also isn't something a single table's migration should unilaterally
    # remove — CASCADE could take out other objects depending on it.
