"""add suggested_action to complaints

Revision ID: ae27e5d73f8c
Revises: 544a1f8f92c8
Create Date: 2026-08-03 00:59:02.186283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae27e5d73f8c'
down_revision: Union[str, Sequence[str], None] = '544a1f8f92c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('suggested_action', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaints', 'suggested_action')
    # ### end Alembic commands ###
